version: '3.8'

services:

  mysql-db:
    container_name: mysql-db
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    env_file:
      .env
    environment:
      - MYSQL_DATABASE=${DB_BASE}
      - MYSQL_ROOT_USERNAME=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    container_name: redis
    image: redis
    command: redis-server
    ports:
      - 6379:6379
    expose:
      - 6379

volumes:
  db:
    driver: local